export const REGISTER_TXT = {
  title: 'Tạo tài khoản mới',
  subtitle: 'Tham gia cộng đồng thời trang REVORA',
  fullNameLabel: 'Họ và tên',
  fullNamePlaceholder: 'Nguyễn Văn A',
  usernameLabel: 'Tên đăng nhập',
  usernamePlaceholder: 'username',
  emailLabel: 'Email',
  emailPlaceholder: 'email@example.com',
  passwordLabel: 'Mật khẩu',
  passwordPlaceholder: '••••••••',
  confirmPasswordLabel: 'Xác nhận mật khẩu',
  confirmPasswordPlaceholder: '••••••••',
  strengthShort: 'Quá ngắn',
  strengthMedium: 'Trung bình',
  strengthStrong: 'Mạnh',
  agreeTerms: 'Tôi đồng ý với ',
  termsOfUse: 'Điều khoản sử dụng',
  and: ' và ',
  privacyPolicy: 'Chính sách bảo mật',
  ofRevora: ' của REVORA',
  submitBtn: 'Tạo Tài Khoản',
  haveAccount: 'Đã có tài khoản? ',
  loginNow: 'Đăng nhập ngay',
  errorDefault: 'Đăng ký thất bại. Vui lòng kiểm tra lại thông tin.',
  validation: {
    fullNameRequired: 'Vui lòng nhập họ và tên.',
    usernameRequired: 'Vui lòng nhập tên đăng nhập.',
    usernameMinLength: 'Tên đăng nhập phải có ít nhất 3 ký tự.',
    usernamePattern: 'Tên đăng nhập chỉ gồm chữ, số và dấu gạch dưới.',
    emailInvalid: 'Email không hợp lệ.',
    passwordMinLength: 'Mật khẩu phải có ít nhất 6 ký tự.',
    confirmPasswordMismatch: 'Mật khẩu xác nhận không khớp.',
    agreeTermsRequired: 'Bạn cần đồng ý với điều khoản sử dụng và chính sách bảo mật của REVORA.',
  }
} as const;
